name: "Pixi: Humble"

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/_pixi.yaml
    with:
      environment: humble
