name: ROS2 Jazzy

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Set up ROS
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      # Step 2: Run ROS CI
      - uses: ros-tooling/action-ros-ci@v0.4
        env:
          HOME: /home/runner
          ROS_HOME: /home/runner/.ros
        with:
          package-name: pj_ros_bridge
          target-ros2-distro: jazzy
