name: "ROS: Kilted"

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/_ros.yaml
    with:
      ros_distro: kilted
      container: rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest
      runner: ubuntu-24.04
